### ISSUE TITLE
setWhite() wrong color

### ISSUE THREAD

**Issue by mwittig** [philip1986/iwy_master#2]
I am wondering about the RGB color values 0, 0, 0 set in the setWhite() function. Shouldn't it be 0xFF,  0xFF, 0xFF instead? See https://github.com/philip1986/iwy_master/blob/master/index.js#L238

**Comment by philip1986** [comment]
Since `this._color` is an instance of [Color](https://github.com/MoOx/color) its not necessary to use hex values. But you are right for devices without an designated WHITE mode the values should be set max (255, 255, 255).

**Comment by philip1986** [comment]
Ok, I fixed the issue and published a new version 0.2.3 of the module
